### PR TITLE
Update Map.py

### PR DESCRIPTION
**Pull request by AdamPlaskitt**
Adding return spell.

### CODE REVIEW

**Comment by Cheerios32** [comment]
A new version of the map, just small bugfixes and logfile update.
BTW, I didn't know about this newer map when I made this :(

Also, when the heck am I getting the chocolate?????

Lastly, I can't upload it, plz help.

**Comment by skifans** [comment]
Hello Peguin, who are you (in the real world)? Its Alex D. I don't know what this thing with chocolate is. When you answer I can set your account to let you push update.

**Comment by Cheerios32** [comment]
Daniel L. Callum owes me chocolate

**Comment by skifans** [comment]
You should now be authorised

**Pull request merged**
