### PR TITLE
Hotfix to get the program running

### PR DESCRIPTION
**Pull request by AdamPlaskitt**
- Removed a global declaration that was causing a syntax error

Signed-off-by: Adam Plaskitt <zfac011@live.rhul.ac.uk>

### CODE REVIEW

**Comment by skifans** [comment]
Well this is something I never expected to see - how are things? You upto something fun?

**Comment by AdamPlaskitt** [comment]
Hey,

Was setting up github for a project this term and had some free time so
thought I'd reminisce. Theres was one line producing a syntax so got rid of
it. There are many bugs though.

And yeah, climbed a lot last week as term hadn't really picked up yet,
though it is starting to this week.

How about you? How are things?

Adam

**Comment by skifans** [comment]
Hi,

Ha, fair enough - interesting we've just started a Python project this term as well, feels like its been a while since I last did much there. 

Thats good, we must have gone back before then as we are about to start are 3rd week.

Good thanks, went mountain biking near Leeds yesterday, sadly isn't too much around Lancaster so thought I'd try them but sadly weren't very good, still at least got I days cycling out of it.

**Comment by AdamPlaskitt** [comment]
Hey,

That's good.

I've come home for the weekend with some uni mates to climb for the
weekend. Which has been good.

My main project this term is a massive group project, but we get to choose
our own stack to use for it.

Got interviews for my year in industry next week as well

Adam

**Comment by skifans** [comment]
Ahh, always good to be back in Sheffield.

Interesting, I'm always annoyed that there are so many different platforms I now have to monitor and have accounts with.

Best of luck!

**Comment by AdamPlaskitt** [comment]
Yeah, we're just using git and heroku for it though.

And I've used them both before atleast

Adam

**Comment by skifans** [comment]
Thats good, never used heroku but seem to be spread among teams, messenger, slack & github (or worse multiple for 1 project) at the moment,

**Comment by AdamPlaskitt** [comment]
Yeah, the stack just keeps expanding.

Though we mainly use discord for communication though, as its bots are
useful.

**Pull request merged**
